name: Deploy to Production

on:
  push:
    branches: [ "master" ]     # change to your default branch if not 'main'
  workflow_dispatch:          # lets you click 'Run workflow' in the UI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test --if-present

  deploy:
    needs: ci
    runs-on: self-hosted      # this targets your private server's runner
    steps:
      - name: Deploy on private server
        env:
          # only needed if your deploy script 'git clone's a PRIVATE repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash /server/ai1/nikita/deploy_calculator.sh
